[functions]
source = "api"
node_bundler = "esbuild"

[functions.build]
command = "npm install"

[functions.include]
files = ["index.js", "package.json", "package-lock.json", "node_modules"]

[functions.environment]
MONGO_URI = "mongodb+srv://silvaliramanoel086:7FOtJhJSCAbw09Pn@catalogoexpress.cp8lvzm.mongodb.net/?retryWrites=true&w=majority&appName=catalogoexpress"
JWT_SECRET = "catalogoexpress_jwt_secret_2025"
